In [8]:
import numpy as np
import random
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline
import seaborn as sns
from scipy import spatial as sp

Generate a random galaxy: locations of planets that will eventually support intelligent life

In [39]:
Nstars = 200

GHZ_inner = 20000.
GHZ_outer = 60000.

r = np.sqrt(np.random.rand(Nstars)*GHZ_outer**2 + GHZ_inner**2)
o = np.random.rand(Nstars)*2.*np.pi

x = r * np.cos(o)  # X position on the galactic plane
y = r * np.sin(o)  # Y position on the galactic plane
acc = np.array([False]*Nstars)    # True:active communicating civilization, False: inactive/inhabited star
t_a = np.zeros(Nstars)  # awakning
t_b = np.zeros(Nstars)  # blackout
N_listening = np.zeros(Nstars) # Number of CETI listening
list_listening = np.zeros(Nstars) # list of CETI listening

In [40]:
t = 0.  # initializea
tau = 5000 #yr, mean lifetime of a ETI
lambd = 50000.  #yr, mean time until next CETI appear
D = 5000.  # light year, maximum distance of detectable signals
tmax = 1000000.  # maximo tiempo que dura la simulación

In [41]:
acc[21] = True
t = 0.
ts = []
t_last_CETI = 0.

In [42]:
def update_awakening(t, t_s_min_idx, t_b_min_idx):
    """Returns the next time at which a new CETI starts transmiting and listening
        and updates the lists.
    """
    
    global t_last_CETI
    global t_start
    global acc
    
    t_last_CETI = t
    i = np.random.choice(range(Nstars))
    t_start[i] = t
    t_s[i] = t + D
    acc[i] = True
    print 'wide awake!', t
    
    
def FCS():
    """Returns the list of the distances from active CETIs and the First Communication Surfaces"""
    
def LCS():
    """Returns the list of the distances from active CETIs and the Last Communication Surfaces"""

def update_blackout(t, t_s_min_idx, t_b_min_idx):
    """Returns the next time at which a CETI ends transmiting and listening"""
    global t_end
    
    t_end[t_b_min_idx] = t
    acc[t_b_min_idx] = False

    print 'blackout', t
    
options = {0 : update_awakening, 1 : update_sphere, 2 : update_blackout}

In [33]:
def Next_awakening():
    t_on_next = np.random.exponential(lambd, 1)
    t_a_min = t_last_CETI + t_on_next
    return(t_a_min)        

def Next_MaxReach():
    T_s = np.ma.array(t_s, mask=~acc)
    t_s_min_idx = np.ma.where(T_s == T_s.min())
    t_s_min = t_s[t_s_min_idx]
    return(t_s_min)

def Next_Blackout():
    T_b = np.ma.array(t_b, mask=~acc)
    t_b_min_idx = np.ma.where(T_b == T_b.min())
    t_b_min = t_b[t_b_min_idx]
    return(t_b_min)

Test individual functions:

In [38]:
t_a_min = Next_awakening()
t_a_min

array([ 63507.84045855])

In [35]:
Next_MaxReach()

array([ 0.])

In [36]:
Next_Blackout()

array([ 0.,  0.])

In [37]:
t = 0.
ts = []
t_last_CETI = 0.

while (t<tmax):
    
    # sortear el tiempo hasta que aparece la próxima CETI
    t_a_min = Next_awakening()
        
    # buscar el proximo tiempo en que se alcanza la esfera
    # completar la máscara con la lista de pares en contacto causal        
    t_s_min = Next_MaxReach()
    
    # buscar el proximo tiempo de desaparicion de una CETI activa
    # completar la máscara con la lista de pares en contacto causal    
    t_b_min = Next_Blackout()
        
#     mins = np.array([t_a_min, t_s_min, t_b_min])    
#     filt = mins > 0.
#     mn = np.ma.array(mins, mask=~filt)    
#     mn_idx = np.ma.where(mn == mn.min())[0][0]  # case to be considered for the next step
        
#     t = t + mins[mn_idx]
#     ts.append(t)
    
#     # Update parameters
#     options[mn_idx](t, t_s_min_idx, t_b_min_idx)    

KeyboardInterrupt: 